import { useState } from 'react'
import Head from 'next/head'
import styles from './index.module.scss'

const Counter = () => {
  const [count, setCount] = useState(0)
  return (
    <div className={styles.counter}>
      <div className={styles.count}>{count}</div>
      <div 
        className={styles.button}
        onClick={() => setCount(count + 1)}
      >
        +
      </div>
      <div 
        className={`${styles.button} ${styles.resetButton}`}
        onClick={() => setCount(0)}
      >
        Reset
      </div>
    </div>
  )
}

export default function Home() {
  const [counters, setCounters] = useState([])

  const resetAllCounters = () => {
    const newCounters = []
    counters.forEach(() => newCounters.push(<Counter key={Math.random()} />))
    setCounters(newCounters)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div 
        className={styles.button}
        onClick={() => setCounters([...counters, <Counter />])}
      >
        Add New Counter
      </div>
      <div 
        className={styles.button}
        onClick={resetAllCounters}
      >
        Reset All
      </div>
      <div className={styles.countersContainer}>
        {counters}
      </div>

    </div>
  )
}
